### ISSUE TITLE
Throw error when inserted node goes out the number of nodes

### ISSUE THREAD

**Issue by EnricoMingo** [FrancescoRuscelli/horizon#18]
I went through this using the following command:
```q.setBounds(qf, qf, nodes=ns+1)```
with ```ns``` the number of nodes used to instantiate the problem.
This should throw an error (check also other methods).

**Comment by EnricoMingo** [comment]
@FrancescoRuscelli Did you manage to solve this?

**Comment by FrancescoRuscelli** [comment]
solved in 5b20f40e26a944b7c691a06d9ed83adece1a1810
