### ISSUE TITLE
make solver interchangeable

### ISSUE THREAD

**Issue by FrancescoRuscelli** [FrancescoRuscelli/horizon#3]
give the possibility to the user to select the solver and add options

**Comment by EnricoMingo** [comment]
I think we can consider this solved for the moment. I'll close.

**Comment by FrancescoRuscelli** [comment]
I reopen this in light of an error using the casadi sqp: the solver, once built, does not accept the parameters argument. We should find a way to standardize all the possible solvers or something on these lines.

**Comment by FrancescoRuscelli** [comment]
This issue is similar to #15
