### ISSUE TITLE
add management of bounds

### ISSUE THREAD

**Issue by FrancescoRuscelli** [FrancescoRuscelli/horizon#4]
Right now only "lists" can be inserted as bounds. Change it to iterable or something similar

**Comment by federicoruggeri** [comment]
It would be useful to provide all expected case studies. For instance:
1. Full range (to avoid full enumeration)
2. Sparse non-adjacent points
3. Range with exceptions (to avoid multiple splits)

Does it make sense? 
Thanks for the support and courtesy
